updates:
  - directory: /
    open-pull-requests-limit: 3
    package-ecosystem: pip
    schedule:
      interval: weekly
    labels:
      - "dependabot"
      - "dependencies"
  - directory: /
    open-pull-requests-limit: 3
    package-ecosystem: github-actions
    schedule:
      interval: weekly
    labels:
      - "dependabot"
      - "dependencies"
version: 2
