version: '3'

services:

  opensearch:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SECURE_INTEGRATION=${SECURE_INTEGRATION:-false}
        - OPENSEARCH_VERSION=${OPENSEARCH_VERSION:-latest}
    command: /usr/share/opensearch/opensearch-run.sh
    ports:
      - "9200:9200"
    user: opensearch
