[tool.poetry]
name = "package"
version = "0.1.0"
description = "OpenSearch samples."
authors = ["Daniel Doubrovkine <dblock@dblock.org>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
opensearch-py = { path = "../", extras=["async"], develop = true }
boto3 = "^1.28"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
