# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/services/search_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/services/search_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.schemas import common_pb2 as protos_dot_schemas_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$protos/services/search_service.proto\x12!org.opensearch.protobufs.services\x1a\x1bprotos/schemas/common.proto2\xdb\x01\n\rSearchService\x12]\n\x06Search\x12\'.org.opensearch.protobufs.SearchRequest\x1a(.org.opensearch.protobufs.SearchResponse\"\x00\x12k\n\x12ServerStreamSearch\x12\'.org.opensearch.protobufs.SearchRequest\x1a(.org.opensearch.protobufs.SearchResponse\"\x00\x30\x01\x42y\n!org.opensearch.protobufs.servicesB\x12SearchServiceProtoP\x01Z>github.com/opensearch-project/opensearch-protobufs/go/servicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.services.search_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!org.opensearch.protobufs.servicesB\022SearchServiceProtoP\001Z>github.com/opensearch-project/opensearch-protobufs/go/services'
  _globals['_SEARCHSERVICE']._serialized_start=105
  _globals['_SEARCHSERVICE']._serialized_end=324
# @@protoc_insertion_point(module_scope)
