name: Delete merged branch of the backport PRs
on: 
  pull_request:
    types:
      - closed
  
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.head.ref,'backport/')
    steps:
      - name: Delete merged branch
        uses: SvanBoxel/delete-merged-branch@2b5b058e3db41a3328fd9a6a58fd4c2545a14353 # main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}