---
get:
  x-endpoint-group: indices.get_settings
  description: Returns settings for one or more indices.
  parameters:
  - in: path
    name: index
    description: A comma-separated list of index names; use `_all` or empty string
      to perform the operation on all indices
    required: true
    schema:
      $ref: "../schemas/_common.yaml#/string_array"
  - in: path
    name: name
    description: The name of the settings that should be included
    required: true
    schema:
      $ref: "../schemas/_common.yaml#/string_array"
  - $ref: "../parameters/query.yaml#/master_timeout"
  - $ref: "../parameters/query.yaml#/cluster_manager_timeout"
  - $ref: "../parameters/query.yaml#/ignore_unavailable"
  - $ref: "../parameters/query.yaml#/allow_no_indices"
  - $ref: "../parameters/query.yaml#/expand_wildcards"
  - $ref: "../parameters/query.yaml#/flat_settings"
  - $ref: "../parameters/query.yaml#/local"
  - $ref: "../parameters/query.yaml#/include_defaults"
