---
post:
  x-endpoint-group: nodes.reload_secure_settings
  description: Reloads secure settings.
  parameters:
  - in: path
    name: node_id
    description: A comma-separated list of node IDs to span the reload/reinit call.
      Should stay empty because reloading usually involves all cluster nodes.
    required: true
    schema:
      $ref: "../schemas/_common.yaml#/string_array"
  - $ref: "../parameters/query.yaml#/timeout"
  requestBody:
    description: An object containing the password for the opensearch keystore
    required: false
    content:
      application/json:
        schema:
          type: object
