---
put:
  x-endpoint-group: indices.put_settings
  description: Updates the index settings.
  parameters:
  - $ref: "../parameters/query.yaml#/master_timeout"
  - $ref: "../parameters/query.yaml#/cluster_manager_timeout"
  - $ref: "../parameters/query.yaml#/timeout"
  - $ref: "../parameters/query.yaml#/preserve_existing"
  - $ref: "../parameters/query.yaml#/ignore_unavailable"
  - $ref: "../parameters/query.yaml#/allow_no_indices"
  - $ref: "../parameters/query.yaml#/expand_wildcards"
  - $ref: "../parameters/query.yaml#/flat_settings"
  requestBody:
    description: The index settings to be updated
    required: true
    content:
      application/json:
        schema:
          type: object
get:
  x-endpoint-group: indices.get_settings
  description: Returns settings for one or more indices.
  parameters:
  - $ref: "../parameters/query.yaml#/master_timeout"
  - $ref: "../parameters/query.yaml#/cluster_manager_timeout"
  - $ref: "../parameters/query.yaml#/ignore_unavailable"
  - $ref: "../parameters/query.yaml#/allow_no_indices"
  - $ref: "../parameters/query.yaml#/expand_wildcards"
  - $ref: "../parameters/query.yaml#/flat_settings"
  - $ref: "../parameters/query.yaml#/local"
  - $ref: "../parameters/query.yaml#/include_defaults"
